### ISSUE TITLE
Crash with `ReferenceError: Headers is not defined`

### ISSUE THREAD

**Issue by leplatrem** [mozilla/remote-settings-ondemand-crashes#1]
Job is deployed and runs. Now facing this error:

```
2024-11-08 13:00:02.760
cron-remote-settings-ondemand-…
ReferenceError: Headers is not defined
    at getCrashIds (file:///app/update_remote_settings_records.mjs:105:19)
    at update (file:///app/update_remote_settings_records.mjs:75:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by afranchuk** [comment]
Hmm. I've run it locally pointing at staging many times, that's surprising.

**Comment by afranchuk** [comment]
Ah, it's probably an issue with using an old version of node.

**Comment by afranchuk** [comment]
The v1.1.1 tag should fix this.

**Comment by leplatrem** [comment]
Seems to have worked, but there is now another crash. Will open other issue
